version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
